version: '3'
services:
  devise-db:
    image: postgres
    container_name: devise-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  devise-web:
    build: .
    container_name: devise-web
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3003:3000"
    depends_on:
      - devise-db
